# Файл nginx-ingress для использования в helm.
# Команда применения:
# kubectl create namespace m && helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx/
# && helm repo update
# && helm install nginx ingress-nginx/ingress-nginx --namespace m -f nginx-ingress.yaml
controller:
    kind: DaemonSet

    reportNodeInternalIp: true

    hostPort:
        enabled: true
        ports:
            http: 80
            https: 443

    service:
        type: NodePort