apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-docker-ingress
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "arch.homework"
      http:
        paths:
          - path: "/(.*)"
            backend:
              service:
                name: otus-docker-service
                port:
                  number: 80
            pathType: Prefix
          - path: "/otusapp/[A-Za-z]+/(.*)"
            backend:
              service:
                name: otus-docker-service
                port:
                  number: 80
            pathType: Prefix